---
proxmox:
  hosts:
    pve:
      ansible_host: 192.168.50.3
kubernetes:
  children:
    control:
      hosts:
        k3s-control-0:
          ansible_host: 192.168.40.100
        k3s-control-1:
          ansible_host: 192.168.40.101
        k3s-control-2:
          ansible_host: 192.168.40.102
    worker:
      hosts:
        k3s-worker-3:
          ansible_host: 192.168.40.103
        k3s-worker-4:
          ansible_host: 192.168.40.104
        k3s-worker-5:
          ansible_host: 192.168.40.105
