---
- name: Destroy cluster
  hosts: kubernetes
  become: true
  any_errors_fatal: true

  tasks:
    - name: Check if cluster is installed
      check_mode: false
      ansible.builtin.stat:
        path: /etc/rancher/k3s/config.yaml
      register: k3s_installed

    - name: Stop Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: stopped
      when: k3s_installed is true

    - name: Uninstall Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: uninstalled

    - name: Flush iptables
      ansible.builtin.iptables:
        table: "{{ item }}"
        flush: true
      loop: ["filter", "nat", "mangle", "raw"]

    - name: Networking | Flush ip6tables
      ansible.builtin.iptables:
        table: "{{ item }}"
        flush: true
        ip_version: ipv6
      loop: ["filter", "nat", "mangle", "raw"]


    - name: Reboot nodes
      ansible.builtin.reboot:
        msg: Rebooting nodes
        reboot_timeout: 3600
