---
- name: Patch system updates
  hosts: kubernetes
  become: true

  tasks:
  - name: Upgrade the OS (apt-get dist-upgrade)
    ansible.builtin.apt:
      upgrade: dist
      update_cache: yes

  - name: Check if a reboot is needed for Ubuntu
    register: reboot_required_file
    ansible.builtin.stat:
      path: /var/run/reboot-required
      get_checksum: no

  - name: Reboot nodes
    ansible.builtin.reboot:
      msg: Rebooting nodes
    when: reboot_required_file.stat.exists
