---
- name: Destroy cluster
  hosts: kubernetes
  become: true
  any_errors_fatal: true

  tasks:
    - name: Stop Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: stopped

    - name: Uninstall Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: uninstalled
