---
- name: Build K3s cluster with a HA control plane using embedded etcd
  hosts: kubernetes
  become: true
  any_errors_fatal: true

  tasks:
    - name: Install Kubernetes
      ansible.builtin.include_role:
        name: xanmanning.k3s
        public: true
      vars:
        k3s_state: installed
